# 🎲 Mastering Random Number Generation in Python

**Welcome!** This notebook explores the world of random number generation in Python. We'll cover standard pseudo-random numbers for simulations and modeling, cryptographically secure random numbers for security-sensitive applications, and efficient random number generation for numerical arrays using NumPy.

**Target Audience:** Python developers needing to generate random data for simulations, sampling, security tokens, testing, or numerical computation.

**Learning Objectives:**
*   Understand the difference between Pseudo-Random Number Generators (PRNGs) and Cryptographically Secure PRNGs (CSPRNGs).
*   Utilize the `random` module for common PRNG tasks (uniform, integer, choice, shuffle).
*   Understand the concept of seeding PRNGs (`random.seed()`) for reproducibility.
*   Generate cryptographically secure random numbers using the `secrets` module.
*   Leverage `numpy.random.Generator` for efficient generation of random NumPy arrays with various distributions.
*   Understand seeding practices for NumPy's modern random number generation.
*   Identify best practices and common pitfalls in random number generation.

## 1. Introduction: What is "Random" in Computing?

True randomness is surprisingly hard to achieve. Most random numbers generated by computers are actually **pseudo-random**.

*   **Pseudo-Random Number Generators (PRNGs):** These algorithms produce sequences of numbers that *appear* random but are actually deterministic. Given the same starting point (the **seed**), a PRNG will always produce the exact same sequence of numbers. This is useful for simulations and testing where reproducibility is needed.
*   **Cryptographically Secure PRNGs (CSPRNGs):** These are designed to be unpredictable, even if an attacker knows the algorithm and some previously generated numbers. They often rely on sources of entropy from the operating system (e.g., mouse movements, network packet timings, hardware random number generators). Essential for security applications.

**Analogy: The Dice Roller**

*   **PRNG (`random` module):** Imagine a mechanical dice-rolling machine. It produces seemingly random results, but if you know exactly how it started (the seed) and its internal mechanics, you could predict every future roll. Great for playing a board game repeatably for testing rules.
*   **CSPRNG (`secrets` module):** Imagine rolling physical dice influenced by many unpredictable factors (air currents, microscopic imperfections, the exact way you shake them). It's extremely hard to predict the outcome, making it suitable for generating lottery numbers or security keys where unpredictability is paramount.

## 2. The `random` Module: Standard Pseudo-Random Numbers

This module implements PRNGs based on the Mersenne Twister algorithm. It's suitable for modeling, simulation, games, and other non-security-critical applications where reproducibility might be desired.

**Key Functions:**

In [1]:
import random
from typing import List, Sequence, TypeVar

# Generic TypeVar for sequence functions
T = TypeVar('T')

# --- Generating Floats --- 
print("--- Random Floats ---")
# random() -> float in [0.0, 1.0)
rand_float = random.random()
print(f"random.random(): {rand_float:.6f}")

# uniform(a, b) -> float in [a, b] or [a, b) depending on rounding
rand_uniform = random.uniform(10, 20) # Float between 10 and 20
print(f"random.uniform(10, 20): {rand_uniform:.6f}")

# --- Generating Integers --- 
print("\n--- Random Integers ---")
# randint(a, b) -> integer N such that a <= N <= b (inclusive)
rand_int = random.randint(1, 6) # Simulate a die roll
print(f"random.randint(1, 6): {rand_int}")

# randrange(start, stop[, step]) -> integer from range(start, stop, step)
# Excludes the 'stop' value
rand_range_excl = random.randrange(1, 7) # Equivalent to randint(1, 6)
print(f"random.randrange(1, 7): {rand_range_excl}")
rand_range_step = random.randrange(0, 101, 10) # Random multiple of 10 up to 100
print(f"random.randrange(0, 101, 10): {rand_range_step}")

# --- Working with Sequences --- 
print("\n--- Sequence Operations ---")
my_list = ['A', 'B', 'C', 'D', 'E', 'F']
my_tuple = (10, 20, 30, 40, 50)
my_string = "abcdefg"

# choice(seq) -> random element from non-empty sequence
chosen_item: str = random.choice(my_list)
print(f"random.choice({my_list}): {chosen_item}")
chosen_num: int = random.choice(my_tuple)
print(f"random.choice({my_tuple}): {chosen_num}")
chosen_char: str = random.choice(my_string)
print(f"random.choice('{my_string}'): {chosen_char}")

# choices(population, weights=None, *, cum_weights=None, k=1) 
# -> list of k elements chosen WITH replacement (can have duplicates)
# Optional weights allow biasing the choice
choices_list: List[str] = random.choices(my_list, k=3)
print(f"random.choices({my_list}, k=3): {choices_list}")
choices_weighted: List[str] = random.choices(my_list, weights=[1, 1, 10, 1, 1, 1], k=3)
print(f"random.choices (weighted towards C): {choices_weighted}")

# sample(population, k) -> list of k unique elements chosen WITHOUT replacement
sample_list: List[str] = random.sample(my_list, k=3)
print(f"random.sample({my_list}, k=3): {sample_list}")

# shuffle(x) -> shuffles sequence x IN PLACE
shuffle_list = my_list.copy() # Work on a copy to preserve original
print(f"Original list before shuffle: {shuffle_list}")
random.shuffle(shuffle_list)
print(f"List after random.shuffle(): {shuffle_list}")

# --- Other Distributions --- 
print("\n--- Other Distributions ---")
# normalvariate(mu, sigma) -> float from Normal distribution
normal_val = random.normalvariate(mu=0, sigma=1) # Standard normal
print(f"random.normalvariate(0, 1): {normal_val:.6f}")

# Many other distributions available: lognormvariate, expovariate, gammavariate, etc.
exp_val = random.expovariate(lambd=1.5)
print(f"random.expovariate(1.5): {exp_val:.6f}")

--- Random Floats ---
random.random(): 0.287983
random.uniform(10, 20): 19.536664

--- Random Integers ---
random.randint(1, 6): 1
random.randrange(1, 7): 6
random.randrange(0, 101, 10): 50

--- Sequence Operations ---
random.choice(['A', 'B', 'C', 'D', 'E', 'F']): C
random.choice((10, 20, 30, 40, 50)): 50
random.choice('abcdefg'): d
random.choices(['A', 'B', 'C', 'D', 'E', 'F'], k=3): ['D', 'F', 'D']
random.choices (weighted towards C): ['C', 'C', 'C']
random.sample(['A', 'B', 'C', 'D', 'E', 'F'], k=3): ['A', 'D', 'C']
Original list before shuffle: ['A', 'B', 'C', 'D', 'E', 'F']
List after random.shuffle(): ['F', 'B', 'C', 'E', 'D', 'A']

--- Other Distributions ---
random.normalvariate(0, 1): -0.807819
random.expovariate(1.5): 0.653242


### 2.1 Seeding the PRNG (`random.seed()`)

As PRNGs are deterministic, providing the same seed guarantees the same sequence of subsequent random numbers. This is crucial for debugging, testing, and reproducible simulations.

*   If `seed()` is called with an integer or other hashable object, it initializes the generator.
*   If called with no argument or `None`, the generator is initialized with a system-dependent source of randomness (e.g., current time, OS entropy).
*   **Best Practice:** Seed *once* at the beginning of your script/session if you need reproducibility. Re-seeding frequently can reduce the statistical quality of the random numbers.

In [2]:
import random

def generate_sequence(seed_value):
    print(f"\n--- Seeding with: {seed_value} ---")
    random.seed(seed_value)
    print(f"  random(): {random.random():.5f}")
    print(f"  randint(1, 10): {random.randint(1, 10)}")
    print(f"  choice('ABC'): {random.choice('ABC')}")

# Generate sequence with seed 42
generate_sequence(42)

# Generate another sequence with seed 123
generate_sequence(123)

# Generate sequence with seed 42 again - should be identical to the first run
generate_sequence(42)

# Reset seed based on system time (less reproducible)
generate_sequence(None) 


--- Seeding with: 42 ---
  random(): 0.63943
  randint(1, 10): 1
  choice('ABC'): C

--- Seeding with: 123 ---
  random(): 0.05236
  randint(1, 10): 2
  choice('ABC'): B

--- Seeding with: 42 ---
  random(): 0.63943
  randint(1, 10): 1
  choice('ABC'): C

--- Seeding with: None ---
  random(): 0.95401
  randint(1, 10): 3
  choice('ABC'): A


## 3. The `secrets` Module: Cryptographically Secure Randomness

**Use Case:** When unpredictability is paramount – generating passwords, security tokens, session keys, cryptographic nonces, etc.

The `secrets` module uses the best available source of randomness provided by the operating system (e.g., `/dev/urandom` on Linux/macOS, `CryptGenRandom` on Windows). You **do not** (and cannot) seed it.

**Key Functions:**

In [3]:
import secrets
import string # For character sets

print("--- secrets Module Examples ---")

# --- Generating Random Integers --- 
# randbelow(n) -> int in [0, n)
secure_int = secrets.randbelow(100) # Secure random int from 0 to 99
print(f"secrets.randbelow(100): {secure_int}")

# randbits(k) -> int with k random bits
secure_bits = secrets.randbits(32) # Secure 32-bit integer
print(f"secrets.randbits(32): {secure_bits} (Binary: {secure_bits:032b})")

# --- Generating Random Bytes --- 
# token_bytes([nbytes=None]) -> random byte string
secure_token_bytes = secrets.token_bytes(16) # 16 secure random bytes
print(f"secrets.token_bytes(16): {secure_token_bytes}")

# --- Generating Tokens (Strings) --- 
# token_hex([nbytes=None]) -> random hex string
secure_hex_token = secrets.token_hex(16) # 32 hex characters
print(f"secrets.token_hex(16): {secure_hex_token}")

# token_urlsafe([nbytes=None]) -> random URL-safe text string
secure_url_token = secrets.token_urlsafe(16) # Base64 encoded, URL-safe characters
print(f"secrets.token_urlsafe(16): {secure_url_token}")

# --- Choosing from Sequences Securely --- 
# choice(seq) -> secure random element
secure_choice = secrets.choice(['admin', 'user', 'guest'])
print(f"secrets.choice(['admin', ...]): {secure_choice}")

# --- Generating Secure Passwords (Example) --- 
alphabet = string.ascii_letters + string.digits + string.punctuation
password_length = 12
# Use secrets.choice repeatedly for strong password generation
secure_password = ''.join(secrets.choice(alphabet) for _ in range(password_length))
print(f"Generated secure password: {secure_password}")

--- secrets Module Examples ---
secrets.randbelow(100): 74
secrets.randbits(32): 1933334085 (Binary: 01110011001111000101011001000101)
secrets.token_bytes(16): b'\xc3\xb9\xeb\xa4f\x08\xbc\xc4\xe5K\x0f\x1c\x8d\x91b\xd7'
secrets.token_hex(16): 5071c2a6b19ae6a30d6b3463f2bfe9cf
secrets.token_urlsafe(16): SK-pDbZYIjUY6ssmUImKpg
secrets.choice(['admin', ...]): guest
Generated secure password: &9B9.u@'9PqT


**Key Takeaway:** Use `random` for simulation and modeling. Use `secrets` for anything security-related.

## 4. NumPy Random Sampling (`numpy.random`)

NumPy is the fundamental package for numerical computing in Python. Its `numpy.random` sub-module provides efficient generation of arrays of random numbers from various distributions.

**Modern NumPy (Recommended): `numpy.random.Generator`**
Since NumPy 1.17, the recommended approach is to create an instance of the `Generator` class using `np.random.default_rng()` and call methods on that instance. This offers better statistical properties and reproducibility compared to the older legacy API (`np.random.rand()`, `np.random.randn()`, etc.).

**Legacy NumPy API:** Functions like `np.random.rand()`, `np.random.randint()`, `np.random.randn()`, `np.random.shuffle()`, and `np.random.seed()` directly modify a global hidden state. While still functional, the `Generator` approach is preferred for clarity, control, and future compatibility.

In [4]:
import numpy as np

# --- Modern API: Using Generator --- 
print("--- NumPy Modern Random API (Generator) ---")

# Create a default Generator instance (uses PCG64 algorithm by default)
# You can provide a seed for reproducibility
rng = np.random.default_rng(seed=42)

# random(size=None, dtype=np.float64, out=None) -> floats in [0.0, 1.0)
random_floats = rng.random(size=5)
print(f"rng.random(size=5):\n{random_floats}")
random_matrix = rng.random(size=(2, 3)) # 2x3 matrix
print(f"\nrng.random(size=(2, 3)):\n{random_matrix}")

# integers(low, high=None, size=None, dtype=np.int64, endpoint=False)
# Generates random integers from low (inclusive) to high (exclusive by default).
# If high=None, generates from [0, low).
random_ints = rng.integers(low=1, high=7, size=10) # 10 dice rolls
print(f"\nrng.integers(1, 7, size=10):\n{random_ints}")
random_ints_endpoint = rng.integers(low=1, high=6, size=10, endpoint=True) # Includes high
print(f"rng.integers(1, 6, size=10, endpoint=True):\n{random_ints_endpoint}")

# standard_normal(size=None, dtype=np.float64, out=None)
# Samples from the standard normal distribution (mean=0, std=1).
normal_values = rng.standard_normal(size=(2, 2))
print(f"\nrng.standard_normal(size=(2, 2)):\n{normal_values}")

# normal(loc=0.0, scale=1.0, size=None) -> samples from N(loc, scale^2)
custom_normal = rng.normal(loc=10.0, scale=2.0, size=5) # Mean 10, StdDev 2
print(f"\nrng.normal(loc=10, scale=2, size=5):\n{custom_normal}")

# choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
# Generates a random sample from a given 1-D array 'a'.
options = ['rock', 'paper', 'scissors']
choices_np = rng.choice(options, size=5) # With replacement by default
print(f"\nrng.choice({options}, size=5):\n{choices_np}")
choices_no_replace = rng.choice(options, size=2, replace=False)
print(f"rng.choice({options}, size=2, replace=False):\n{choices_no_replace}")

# shuffle(x, axis=0) -> shuffles array x IN PLACE along the specified axis
my_array = np.arange(10)
print(f"\nOriginal array: {my_array}")
rng.shuffle(my_array)
print(f"Shuffled array: {my_array}")

# permutation(x, axis=0) -> returns a shuffled COPY of array x
my_array2 = np.arange(5)
permuted_array = rng.permutation(my_array2)
print(f"\nOriginal array 2: {my_array2}") # Unchanged
print(f"Permuted copy: {permuted_array}")

# --- Seeding with Generator --- 
# Seeding is done when creating the Generator instance
rng1 = np.random.default_rng(123)
rng2 = np.random.default_rng(123)
print("\n--- NumPy Reproducibility ---")
print(f"rng1 first random: {rng1.random():.5f}")
print(f"rng2 first random: {rng2.random():.5f}") # Should be the same
print(f"rng1 second random: {rng1.random():.5f}")
print(f"rng2 second random: {rng2.random():.5f}") # Should be the same

--- NumPy Modern Random API (Generator) ---
rng.random(size=5):
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]

rng.random(size=(2, 3)):
[[0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802]]

rng.integers(1, 7, size=10):
[2 6 5 4 3 5 4 3 3 2]
rng.integers(1, 6, size=10, endpoint=True):
[1 4 6 1 6 5 2 4 1 5]

rng.standard_normal(size=(2, 2)):
[[-0.68092954  1.22254134]
 [-0.15452948 -0.42832782]]

rng.normal(loc=10, scale=2, size=5):
[ 9.2957329  11.06461837 10.73088813 10.82546522 10.86164201]

rng.choice(['rock', 'paper', 'scissors'], size=5):
['scissors' 'scissors' 'paper' 'scissors' 'paper']
rng.choice(['rock', 'paper', 'scissors'], size=2, replace=False):
['scissors' 'rock']

Original array: [0 1 2 3 4 5 6 7 8 9]
Shuffled array: [3 7 4 9 1 8 6 2 0 5]

Original array 2: [0 1 2 3 4]
Permuted copy: [0 4 3 2 1]

--- NumPy Reproducibility ---
rng1 first random: 0.68235
rng2 first random: 0.68235
rng1 second random: 0.05382
rng2 second random: 0.05382


## 5. Best Practices & Enterprise Considerations

1.  **Choose the Right Tool:**
    *   Use `secrets` for security-sensitive applications (passwords, tokens, cryptography).
    *   Use `random` for general-purpose modeling, simulations, games, and non-critical sampling where reproducibility might be needed.
    *   Use `numpy.random.Generator` for efficient generation of random arrays for numerical computation, especially involving specific distributions.
2.  **Seeding Strategy:**
    *   **DO NOT** seed `secrets`. It relies on OS entropy.
    *   Seed `random` and `numpy.random.Generator` *once* at the start if you need reproducibility (e.g., for testing or specific simulations).
    *   Avoid frequent re-seeding within the same run, as it can harm randomness quality.
    *   For NumPy, prefer creating distinct `Generator` instances (possibly with different seeds if needed for parallel streams) over using the legacy global state.
3.  **Understand Distributions:** When using `random` or `numpy.random`, be clear about which distribution you need (uniform, normal, exponential, etc.) and understand its parameters (e.g., `mu`/`loc`, `sigma`/`scale`).
4.  **Security:** Never use `random` module outputs for cryptographic purposes. Attackers might be able to predict the sequence.
5.  **Sampling:** Be aware of the difference between sampling *with* replacement (`random.choices`, `numpy.random.choice(replace=True)`) and *without* replacement (`random.sample`, `numpy.random.choice(replace=False)`).
6.  **Large Datasets (NumPy):** NumPy's vectorized operations are highly efficient for generating large amounts of random data compared to generating numbers one by one with the `random` module in a loop.

## 6. Pitfalls and Common Interview Questions

**Common Pitfalls:**

*   **Using `random` for Security:** The most critical pitfall. Never use `random` for passwords, keys, etc. Use `secrets`.
*   **Seeding Incorrectly:** Seeding `secrets` (impossible), seeding `random`/`numpy` too often, or seeding the wrong generator (e.g., seeding `random` but expecting `numpy` results to be reproducible).
*   **Misunderstanding Ranges:** Mixing up inclusive (`randint`) vs. exclusive (`randrange`, `np.random.integers` default) upper bounds.
*   **Confusing `shuffle` vs. `permutation`:** `shuffle` modifies in-place, `permutation` returns a copy.
*   **Floating Point Precision:** Remember standard floating-point limitations apply.
*   **Performance:** Using `random` in loops for large array generation instead of optimized NumPy functions.

**Common Interview Questions:**

1.  When should you use the `secrets` module versus the `random` module?
2.  What does "pseudo-random" mean?
3.  How do you make random number generation reproducible in Python's `random` module? Why might you want to do this?
4.  Can you seed the `secrets` module? Why or why not?
5.  How do you generate a random integer within a specific range (inclusive)?
6.  How do you pick a random element from a list?
7.  What's the difference between `random.sample()` and `random.choices()`?
8.  How do you generate an array of random floating-point numbers between 0 and 1 using NumPy?
9.  What is the recommended way to generate random numbers in modern NumPy (since v1.17)? (`np.random.default_rng`)
10. How would you generate random numbers following a standard normal distribution using NumPy?

## 7. Challenge: Simple Password Generator & Data Simulation

**Goal:** Create two functions demonstrating the appropriate use of `secrets` and `numpy.random`.

**Tasks:**

1.  **Secure Password Generator:**
    *   Write a function `generate_secure_password(length: int = 14) -> str`.
    *   Use the `secrets` module.
    *   Ensure the password includes a mix of uppercase letters, lowercase letters, digits, and punctuation (use the `string` module constants).
    *   Make sure the resulting password has the specified `length`.
    *   (Bonus: Add checks to guarantee at least one character from each category if needed, though pure random choice might be sufficient for length >= 14).
2.  **Simulate Sensor Readings:**
    *   Write a function `simulate_sensor_data(num_readings: int, mean_temp: float, std_dev_temp: float, seed: Optional[int] = None) -> np.ndarray`.
    *   Use `numpy.random.default_rng()` (seed it if `seed` is provided).
    *   Generate `num_readings` temperature values following a normal distribution with the specified mean (`mean_temp`) and standard deviation (`std_dev_temp`).
    *   Return the readings as a NumPy array.

**Test:** Call both functions and print their results. Call the simulation function twice with the same seed to verify reproducibility.

In [5]:
# --- Solution Space for Challenge ---
import secrets
import string
import numpy as np
from typing import Optional
import logging

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s', force=True)

# --- Task 1: Secure Password Generator ---
def generate_secure_password(length: int = 14) -> str:
    """Generates a cryptographically secure password using secrets."""
    if length < 8: # Basic minimum length check
        logging.warning("Password length should ideally be 8 or more.")
        length = 8 
        
    # Define the character set
    alphabet = string.ascii_letters + string.digits + string.punctuation
    
    while True:
         # Generate password using secrets.choice
        password = ''.join(secrets.choice(alphabet) for _ in range(length))
        
        # Optional Bonus: Ensure character diversity (example implementation)
        # This makes it slightly less purely random but meets common requirements
        has_lower = any(c in string.ascii_lowercase for c in password)
        has_upper = any(c in string.ascii_uppercase for c in password)
        has_digit = any(c in string.digits for c in password)
        has_punct = any(c in string.punctuation for c in password)
        
        if has_lower and has_upper and has_digit and has_punct:
            return password
        # If diversity check fails, the loop continues to generate a new password
        # logging.debug("Generated password lacked diversity, retrying...")


# --- Task 2: Simulate Sensor Readings ---
def simulate_sensor_data(num_readings: int, 
                         mean_temp: float, 
                         std_dev_temp: float, 
                         seed: Optional[int] = None) -> np.ndarray:
    """Simulates sensor temperature readings using NumPy PRNG."""
    if num_readings <= 0:
        return np.array([])
    if std_dev_temp < 0:
         raise ValueError("Standard deviation cannot be negative.")
         
    # Create a Generator instance, seeding if requested
    rng = np.random.default_rng(seed=seed)
    logging.info(f"Simulating {num_readings} readings. Mean={mean_temp}, StdDev={std_dev_temp}, Seed={seed}")
    
    # Generate data from a normal distribution
    readings = rng.normal(loc=mean_temp, scale=std_dev_temp, size=num_readings)
    return readings

# --- Testing --- 
print("--- Testing Functions ---")

# Test Password Generator
password_1 = generate_secure_password(16)
password_2 = generate_secure_password(10)
print(f"Generated Password 1 (len 16): {password_1}")
print(f"Generated Password 2 (len 10): {password_2}")

# Test Sensor Simulation
sim_readings_1 = simulate_sensor_data(num_readings=5, mean_temp=20.0, std_dev_temp=1.5, seed=123)
print(f"\nSimulated Readings (Seed 123):\n{sim_readings_1}")

sim_readings_2 = simulate_sensor_data(num_readings=5, mean_temp=20.0, std_dev_temp=1.5, seed=999)
print(f"\nSimulated Readings (Seed 999):\n{sim_readings_2}")

sim_readings_3 = simulate_sensor_data(num_readings=5, mean_temp=20.0, std_dev_temp=1.5, seed=123)
print(f"\nSimulated Readings (Seed 123 again):\n{sim_readings_3}")

# Verify reproducibility
assert np.array_equal(sim_readings_1, sim_readings_3)
print("\nReproducibility with seed confirmed.")

--- Testing Functions ---
Generated Password 1 (len 16): kX8b*Z&zS:u8vO$@
Generated Password 2 (len 10): ]qDz?Jt4w}


INFO: Simulating 5 readings. Mean=20.0, StdDev=1.5, Seed=123
INFO: Simulating 5 readings. Mean=20.0, StdDev=1.5, Seed=999
INFO: Simulating 5 readings. Mean=20.0, StdDev=1.5, Seed=123



Simulated Readings (Seed 123):
[18.51631797 19.44832002 21.93188789 20.29096163 21.38034635]

Simulated Readings (Seed 999):
[21.14847335 19.25504898 16.92391536 19.99065411 20.79003008]

Simulated Readings (Seed 123 again):
[18.51631797 19.44832002 21.93188789 20.29096163 21.38034635]

Reproducibility with seed confirmed.


## 8. Conclusion

Python offers flexible and powerful tools for random number generation, but it's crucial to choose the right module for the job. The `secrets` module is essential for security-related tasks requiring unpredictable random numbers. The `random` module provides a versatile toolkit for general-purpose pseudo-random generation in simulations and modeling. For efficient numerical work involving random arrays and diverse distributions, NumPy's modern `random.Generator` API is the recommended approach.

Understanding the difference between PRNGs and CSPRNGs, and mastering seeding techniques for reproducible results when needed, will allow you to confidently incorporate randomness into your Python applications.